### ISSUE TITLE
REF: consider refactoring `CheckAndDo` to be a pytrees node type

### ISSUE THREAD

**Issue by tangkong** [pcdshub/BEAMS#20]
Currently `beams.behavior_tree.CheckAndDo.CheckAndDo` is a custom class that just holds onto a `ConditionNode` and `ActionNode`.  We should consider refactoring this to be a subclass of pytree's `Selector` node directly.  

This could make constructing / serializing trees more natural.

I think it's likely that we'll want to build out a library of "meta-trees".  Name notwithstanding, I imagine these "meta-trees" to be pre-built / parametrized sub trees that we use as shortcuts in constructing our behavior trees.  A `CheckAndDo` is one such example, but I imagine that to be truly aid users we'll want to provide even higher level sub-trees (a "home motor" subtree?  A "bring host up" subtree?)

**Comment by tangkong** [comment]
These probably end up looking like [py_trees.idioms](https://py-trees.readthedocs.io/en/devel/idioms.html)

**Comment by joshc-slac** [comment]
Totally agree it will look a lot like the py_trees idiom [either or](https://py-trees.readthedocs.io/en/devel/idioms.html#either-or) ([[source]](https://github.com/splintered-reality/py_trees/blob/0d5b39f2f6333c504406d8a63052c456c6bd1ce5/py_trees/idioms.py#L97-L198)). 

To be clear pre me implementing this good suggestion, the reason we are not using py_trees idiom either or is that we want the option for further granular control of this type of "meta node" (love the name) without needing to edit the py_trees library ourselves so we will keep it in house (this codebase). 

I am **very** open to better names than `CheckAndDo` fwiw

**Comment by tangkong** [comment]
Totally makes sense.  I was thinking something more like `beams.idioms` to parallel `py_trees.idioms`, with a library of our own meta-nodes / sub-trees
