### ISSUE TITLE
TST: expand serialization / tree generation tests

### ISSUE THREAD

**Issue by tangkong** [pcdshub/BEAMS#31]
## Current Behavior
We have tests, but what about more tests?

## Expected Behavior
Make some tests that test the full suite of node types and idioms

## Context / environment
I didn't want to clutter #30 

## Steps to Reproduce (for bugs)
N/A

## Suggested Solution
Some ideas: (possibly in one big parametrized test)
- Put every node in a sequence
- Run all tests through serialization round trip and get_tree instantiation smoke check
- (Stretch goal) build some real operational trees and mock IOCs to match

**Comment by joshc-slac** [comment]
I would like to close this; but we can always make tests better. the advent of test_tree_config seems to satisfy

**Comment by tangkong** [comment]
I think this is closed by some combination of #67, #47, and #61.  More tests to come of course, but it's a Sisyphean task
