### ISSUE TITLE
ENH: Determine if we want on success / on failure actions encoded into our action nodes OR if we want to be more BT principic

### ISSUE THREAD

**Issue by joshc-slac** [pcdshub/BEAMS#32]
A beauty of software is its all semantics. 

Motivation for this would be "setting another PV on success of actuation of other PV".  

## Current Behavior
Currently our action nodes can only set the PV they also monitor. 

### More BT Principic
This may be okay and force us to be more BT principic. For example we could have a "CheckDoandConditonallyDo" (okay that name sucks but you get the point) 
![image](https://github.com/user-attachments/assets/0aeb6c95-a985-465b-bab3-aea68dc6e669)

Where A1 does an action (sets a PV and monitors success on another PV) should A1 succeed the sequence node will tick A2 which could set a signalling PV for some other IOC

### Slight BT overloading
https://github.com/pcdshub/BEAMS/blob/25611c79a52e452a387d635fc61601caf23db76a/beams/tree_config.py#L169-L173

We could also implement a `termination_action` possibly shared across all ActionItems. This is similar to more "code centric" sequencing implementations. For exampling traversing through a linked list in which the nodes have completion and failure actions. In the same way we are mildly overloading `ConditionItem` above we could add an `ActionItem`.

**Comment by joshc-slac** [comment]
The main heuristic we should use in deciding is "what is most communicative to users, gives them the most control, and encourages the most usability". This _may_ surprisingly lean towards the latter of my suggestions

**Comment by tangkong** [comment]
I believe that with #30, we have successfully decoupled the two.  You can set the termination condition to look at a different PV than the set-action does.

**Comment by joshc-slac** [comment]
Definitely decouples the two; however, what if we want to conditionally perform an action on completion? I agree #30 gives us the infracstructure to chain together actions such that we can have a SuccessCompletion action and a FailureCompletion action within the tree structure. 

We can build more and more complex idioms to capture this. We could still theoretically package it within the action node itself. Whatever we decide lets make it explicit and put slightly more thought into it.

**Comment by ZLLentz** [comment]
I think an important question to answer is: how complex can an action node get before it is more easily understandable as a set of independent notes collected in an idiom? Maybe this gets a bit closer to the philosophical question here, if I'm understanding correctly.

My 2c on the above is that as long as an action node corresponds to a discrete real-life action, it is permissible (and helpful). This is of course pretty broad because there are lots of ways to define actions (write to PV, "move" and wait, run-a-big-script, "collect data", etc.)

**Comment by joshc-slac** [comment]
No longer sure of the utility of this issue. 

I think Robert was 100% correct in that his work on #30 frees us to ask better questions. Also with the way BTs are now executing work it likely makes sense to keep this more BT principic to adhere to the goals of communicability (mainly) and modularity (sort of, mainly to prevent bloat)
