### ISSUE TITLE
TST: Add test artifact ("egg") generator ("chicken")

### ISSUE THREAD

**Issue by tangkong** [pcdshub/BEAMS#52]
## Current Behavior
Our artifacts (test behaviour trees) only exist in json serialized format

## Expected Behavior
We should add a little script to regenerate these, if our dataclass schema ever changes.  It may also be worthwhile adding in-python-memory fixtures for these behaviour trees, in the interest of not going through serialization/deserialization each time.

## Context / environment
Discussion from today's BEAM tagup

## Steps to Reproduce (for bugs)
N/A

## Suggested Solution
Fixtures in conftest.
possibly a `make artifacts` routine

**Comment by joshc-slac** [comment]
adding the make step to #67. I believe we can close this with #61
