### ISSUE TITLE
Ability to simulate a real BT easily || generate moc IOCs from a real world example OR swap in a blackboard equivalent of the tree

### ISSUE THREAD

**Issue by joshc-slac** [pcdshub/BEAMS#53]
## Suggested Solution
We want to keep a 1:1 tree representation. 
Does this require some form of scrapping tool? 
* can we scrape our existing control system?

**Comment by tangkong** [comment]
From our weekly discussion:
The goal is to easily mock a real tree and test/verify its execution logic.  There were a couple of methods proposed for this:
* Create blackboard analogs to our EPICS-communication-enabled tree items.  Alternately: refactor our items to be more one-to-one with the blackboard items.
  * When mocking a tree, we could swap out EPICS-items with Blackboard-items and easily track the variables
  * This might result in us being unsure if the conversion was truly accurate, and was ranked lowest)
* Programmatically stand up a caproto IOC, after scraping all PV instances from items in the tree, then run the tree against that IOC
  * We could isolate communication by using a different port than the normal CA communication
  * We can scrape our controls system to initialize this caproto IOC
* Inject blackboard communication by monkeypatching caget/caput
  * snazzy, fun

All of this is important long term, but w.r.t an MVP is maybe of a lower priority
