### ISSUE TITLE
Would like to re-enable extending baseclass derserialization via apischema

### ISSUE THREAD

**Issue by joshc-slac** [pcdshub/BEAMS#63]
## Current Behavior
All of our serialized items share the same base class, this isn't great for modularity. I would love it to not be the case, but I am also scared of apischema

## Suggested Solution
Have @tangkong do some python magic and make apischema able to deserialize derived classes

**Comment by tangkong** [comment]
I'm a bit confused about this issue.  What do we mean by "modularity" here?  What exactly are we trying to achieve?

You're free to make new `TreeItem` lookalikes, you'll just have to add the shared methods / fields yourself.  You'll also lose the ability to type hint all the TreeItem classes at once without an additional type alias.  

We can already de-serialize child classes of `BaseItem`, I've just had the experience of "grandchildren" not deserializing nicely.

**Comment by joshc-slac** [comment]
Thanks to roberts help this was closed by #67 ; more work can and will be done in extending / granularizing base classes for ActionNodes especially for non EPICS things
