### ISSUE TITLE
JSON generated trees

### ISSUE THREAD

**Issue by joshc-slac** [pcdshub/BEAMS#8]
The best structure of the actual configuration file is slightly eluding me. 

For real, interesting, multilayered trees we probably will just need to explicitly have a list of node objects within the json document that specify their parent child relationships within the tree. 

This likely looks like adding: 
`parent` and `child` fields to the:  `CheckAndDoNodeEntry` class. 
https://github.com/pcdshub/BEAMS/blob/0460058cdb1c1447cea7db0cc3b6a5dc12786d32/beams/tree_generator/TreeSerializer.py#L81-L85

Then making the notion of config document able to hold multiple of these classes. My unfamiliarity with apischema is throwing me off the scent here.

**Comment by tangkong** [comment]
It shouldn't be a problem to have any given `_NodeEntry` hold "children" that are also `_NodeEntry` subclasses.  We do this in atef ([link](https://github.com/pcdshub/atef/blob/11b15c01dfafd9fe3c6d5ea39afd5844c071c339/atef/config.py#L130-L135)) and in the new superscore ([link](https://github.com/pcdshub/superscore/blob/2dbd9e18980b6dd9d7ff27704cc08fdf8aa8f1ce/superscore/model.py#L237-L245))

When you say apischema is throwing you, I take that to mean there's something in deserialization / serialization that's giving you trouble?  If you just create the data structure without caring about apischema, what do you get?

**Comment by joshc-slac** [comment]
This an #18 seem very related.

**Comment by tangkong** [comment]
closed by #30
